server-name=Craft Runtime Test
gamemode=survival
force-gamemode=true
difficulty=peaceful
allow-cheats=true
online-mode=false
allow-list=false
server-port=19140
server-portv6=19141
enable-lan-visibility=false
view-distance=5
tick-distance=4
player-idle-timeout=0
max-players=5
default-player-permission-level=operator
transport=raknet
server-authoritative-movement-strict=false
block-network-ids-are-hashes=true
level-name=RuntimeCraft
